learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('learning_logs.urls'))
]

learning_logs/urls.py
"""Определяет схемы URL для learning_logs"""

from django.urls import path

from . import views

app_name = 'learning_logs'
urlpatterns = [
    # Страница для добавления нового сообщения
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    # Страница редактирования записи
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
    # Удаление записи
    path('delete_entry/<int:entry_id>/', views.delete_entry, name='delete_entry'),
    # Подробная страница одной темы
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    # Страница для добавления новой темы
    path('new_topic/', views.new_topic, name='new_topic'),
    # Удаление темы
    path('delete_topic/<int:topic_id>/', views.delete_topic, name='delete_topic'),
    # Вывод всех тем
    path('topics/', views.topics, name='topics'),
    # Домашняя страница
    path('', views.index, name='index'),
]

users/urls.py
"""Определяет схемы URL для пользователей"""

from django.urls import path
from django.contrib.auth import views as auth_views

from . import views


app_name = 'users'
urlpatterns = [
    # Страница входа
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    # Страница выхода
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    # Страница регистрации
    path('register/', views.register, name='register'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Topic(models.Model):
    """Тема, которую изучает пользователь"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Возвращает строковое представление модели"""
        return self.text


class Entry(models.Model):
    """Информация изученная пользователем по теме"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Возвращает строковое представление модели"""
        if len(self.text) > 50:
            # Если длина текста больше 50 знаков, то обрезаем текст до 50 знаков
            # и добавляем многоточие в конце
            return self.text[:50] + "..."
        else:
            return self.text

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms
from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.shortcuts import render

from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import Topic, Entry
from .forms import TopicForm, EntryForm


# Create your views here.
def index(request):
    """Домашняя страница приложения learning_logs"""
    return render(request, 'learning_logs/index.html')


@login_required
def topics(request):
    """Выводит список тем"""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)


@login_required
def topic(request, topic_id):
    """Выводит одну тему и все её записи"""
    topic = Topic.objects.get(id=topic_id)
    check_topic_owner(topic, request)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)


@login_required
def new_topic(request):
    """Определяет новую тему"""
    if request.method != 'POST':
        # Данные не отправлялись; создается пустая форма
        form = TopicForm()
    else:
        # Отправлены данные POST; обработать данные
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)


@login_required
def delete_topic(request, topic_id):
    try:
        topic = Topic.objects.get(id=topic_id)
        check_topic_owner(topic, request)
        topic.delete()
        return HttpResponseRedirect('/topics')
    except Topic.DoesNotExist:
        return Http404


@login_required
def new_entry(request, topic_id):
    """Добавляет новую запись по конкретной теме"""
    topic = Topic.objects.get(id=topic_id)
    check_topic_owner(topic, request)
    if request.method != 'POST':
        # Данные не отправлялись; создается пустая форма.
        form = EntryForm()
    else:
        # Отправлены данные POST; обработать данные.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic_id]))

    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    """Редактирует существующую запись"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    # Проверка того, что тема принадлежит данному пользователю
    check_topic_owner(topic, request)
    if request.method != 'POST':
        # Исходный запрос; форма заполняется данными текущей записи
        form = EntryForm(instance=entry)
    else:
        # Отправка данных POST; обработать данные
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic.id]))
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)


@login_required
def delete_entry(request, entry_id):
    """Совершает удаление записи"""
    try:
        entry = Entry.objects.get(id=entry_id)
        topic = entry.topic
        topic_id = entry.topic_id
        check_topic_owner(topic, request)
        entry.delete()
        return HttpResponseRedirect(('/topics/{}').format(topic_id))
    except Entry.DoesNotExist:
        return Http404


def check_topic_owner(topic, request):
    """Проверка того, что тема принадлежит данному пользователю"""
    if topic.owner != request.user:
        raise Http404

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect

from django.urls import reverse
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm


# Create your views here.
def register(request):
    """Регистрирует нового пользователя"""
    if request.method != 'POST':
        # Показывать пустую форму регистрации
        form = UserCreationForm
    else:
        # Обработать заполненную форму
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Выполнить вход и перенаправить на домашнюю страницу приложения
            authenticated_user = authenticate(username=new_user.username, password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('learning_logs:index'))
    context = {'form': form}
    return render(request, 'users/register.html', context)

learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Learning Log</title>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

</head>
<body>
    <!-- Статическая навигационная панель -->
    <nav class="navbar navbar-expand-md navbar-light" style="background-color:#e3f2fd;">
        <div class="container">
            <div class="navbar-header">
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                        data-target="#navbar" aria-controls="navbar"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>


                <a class="navbar-brand" href="{% url 'learning_logs:index' %}">Learning Log</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="navbar-nav mr-auto">
                    <li><a class="btn btn-primary btn-sm" href="{% url 'learning_logs:topics' %}"> Topics </a></li>
                </ul>
                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link">Hello, {{ user.username }}. </a></li>
                        <li class="nav-item"><a class="btn btn-outline-info" href="{% url 'users:logout' %}"> Log Out </a></li>
                    {% else %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'users:login' %}"> Log in </a></li>
                        <li class="nav-item"><a class="btn btn-outline-info" href="{% url 'users:register' %}"> Register </a></li>
                    {% endif %}
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </nav>
    <div class="container">
        <div class="page-header">
            {% block header %}{% endblock header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </div> <!-- /container -->
</body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block header %}
    <h2>Edit entry:</h2>
{% endblock header %}

{% block content %}
  <p>
      <a class="badge badge-primary" href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
  </p>

  <form class="form" action="{% url 'learning_logs:edit_entry' entry.id %}" method="post">

      {% csrf_token %}
      {% bootstrap_form form %}
      {% bootstrap_button "Save changes" button_type="submit" button_class="btn-primary" %}
      <a href="{% url 'learning_logs:delete_entry' entry.id %}" class="btn btn-danger">Delete entry</a>
  </form>

{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block header%}
    <div class="jumbotron">
        <h1>Track your learning.</h1>
    </div>
{% endblock header %}
{% block content %}
    <h2><a href="{% url 'users:register' %}">Register an account</a> to make your own Learning Log, and list
    the topics you're learning about.</h2>
    <h2>Whenever you learn something new about a topic, make an entry
        summarizing what you've learned.</h2>
{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block header %}
    <h2>Add a new entry:</h2>
{% endblock header %}

{% block content %}
  <p><a class="badge badge-primary" href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

  <form class="form" action="{% url 'learning_logs:new_entry' topic.id %}" method="post">

      {% csrf_token %}
      {% bootstrap_form form %}
      {% bootstrap_button "Add entry" button_type="submit" button_class="btn-primary" %}

  </form>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block header %}
    <h2>Add a new topic:</h2>
{% endblock header %}

{% block content %}

  <form action="{% url 'learning_logs:new_topic' %}" method="post" class="form">

      {% csrf_token %}
      {% bootstrap_form form %}

      {% buttons %}
            <button name="submit" class="btn btn-primary">Add topic</button>
      {% endbuttons %}
  </form>
{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends "learning_logs/base.html" %}

{% block header %}
    <h2>Topic: {{ topic }}</h2>
    <span>
        <a href="{% url 'learning_logs:delete_topic' topic.id %}" class="badge badge-danger">
            Delete topic
        </a>
    </span>
{% endblock header %}
{% block content %}

    <p>Entries: </p>
    <p>
        <a class="btn btn-primary" href="{% url 'learning_logs:new_entry' topic.id %}">add new entry</a>
    </p>
    <ul>
        {% for entry in entries %}
            <div class="card" style="margin: 10px">
                <div class="card-header">
                    <h3>
                        {{ entry.date_added|date:'M d, Y H:i' }}
                        <small>
                            <a class="btn btn-primary btn-sm" href="{% url 'learning_logs:edit_entry' entry.id %}">edit entry</a>
                        </small>
                    </h3>
                </div>
                <div class="card-body">
                    <p class="card-text">{{ entry.text|linebreaks }}</p>
                    <a href="{% url 'learning_logs:delete_entry' entry.id %}" class="btn btn-danger btn-sm"
                       style="position: absolute; right: 15px; bottom: 15px">Delete entry</a>
                </div>
            </div> <!-- panel -->

        {% empty %}
          There are no entries for this topic yet.
        {% endfor %}
    </ul>
{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block header %}
    <h1>Topics</h1>
{% endblock header %}
{% block content %}

  <ul>
      {% for topic in topics %}
          <li>
              <h3>
                <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
              </h3>
          </li>
      {% empty %}
          <li>No topics have been added yet.</li>
      {% endfor %}
  </ul>
        <h3><a href="{% url 'learning_logs:new_topic' %}">Add a new topic</a></h3>
{% endblock content %}

users/templates/users/login.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block header %}
    <h2>Log in to your account.</h2>
{% endblock header %}

{% block content %}

    <form method="post" action="{% url 'users:login' %}" class="form">

        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button "Log in" button_type="submit" button_class="btn-primary" %}

        <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
    </form>

{% endblock content %}

users/templates/users/register.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block header %}
    <h2>Register your account.</h2>
{% endblock header %}

{% block content %}

    <form class="form" method="post" action="{% url 'users:register' %}">

        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button "Register" button_type="submit" button_class="btn-primary" %}

        <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
    </form>

{% endblock content %}